import './globals.css';
import '../../server.js'
export const metadata = {
  title: 'My Prototype',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  )
}